version: '3'
services:
  postgres: 
    image: postgres:latest
    container_name: postgres
    hostname: tricontainerregistries.azurecr.io
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:latest
    container_name: redis
    hostname: tricontainerregistries.azurecr.io
    volumes:
      - redisdata:/data
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server 
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    image: tricontainerregistries.azurecr.io/api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      # - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
    image: tricontainerregistries.azurecr.io/client
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    # volumes:
    #   - /app/node_modules
    #   - ./worker:/app
    image: tricontainerregistries.azurecr.io/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    image: tricontainerregistries.azurecr.io/nginx
    # ports:
    #   - 3050:80
    depends_on:
      - api
      - client
volumes:
  postgresdata:
    driver: azure_file
    driver_opts:
      share_name: postgresdata
      storage_account_name: tridockervolumes
  redisdata:
    driver: azure_file
    driver_opts:
      share_name: redisdata
      storage_account_name: tridockervolumes