version: '3'
services:
  postgres: 
    image: tridockerreact.azurecr.io/postgres:latest
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: tridockerreact.azurecr.io/redis:latest
    volumes:
      - redisdata:/data
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server 
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    image: tridockerreact.azurecr.io/api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      # - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
    image: tridockerreact.azurecr.io/client
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    # volumes:
    #   - /app/node_modules
    #   - ./worker:/app
    image: tridockerreact.azurecr.io/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    image: tridockerreact.azurecr.io/nginx
    ports:
      - 3050:80
    depends_on:
      - api
      - client
volumes:
  postgresdata:
  redisdata: